---
- name: Update apt cache.
  ansible.builtin.apt: update_cache=true
  when: ansible_os_family == 'Debian'
  changed_when: false

- name: Install test dependencies (Debian).
  ansible.builtin.package: name=netcat state=present
  when: ansible_os_family == 'Debian'

- name: Install test dependencies (RedHat).
  ansible.builtin.package: name=nc state=present
  when: ansible_os_family == 'RedHat'

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure munin-node is installed (RedHat).
  ansible.builtin.yum: name=munin-node state=present enablerepo=epel
  when: ansible_os_family == 'RedHat'

- name: Ensure munin-node is installed (Debian).
  ansible.builtin.apt: name=munin-node state=present
  when: ansible_os_family == 'Debian'

- name: Copy munin-node configuration.
  ansible.builtin.template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart munin-node

- name: Generate plugin configuration.
  ansible.builtin.template:
    src: plugin-conf.j2
    dest: /etc/munin/plugin-conf.d/ansible.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart munin-node

- name: Install extra plugins.
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ munin_plugin_src_path }}{{ item.src | basename }}"
    mode: '0755'
  with_items: "{{ munin_node_install_plugins }}"
  when: item.src is defined
  notify: Restart munin-node

- name: Install extra remote plugins.
  ansible.builtin.get_url:
    url: "{{ item.remote_src }}"
    dest: "{{ munin_plugin_src_path }}{{ item.remote_src | basename }}"
    mode: '0755'
  with_items: "{{ munin_node_install_plugins }}"
  when: item.remote_src is defined
  notify: Restart munin-node

- name: Enable additional plugins.
  ansible.builtin.file:  # noqa 208
    path: "{{ munin_plugin_dest_path }}{{ item.name }}"
    src: "{{ munin_plugin_src_path }}{{ item.plugin | default( item.name ) }}"
    state: link
  with_items: "{{ munin_node_plugins }}"
  notify: Restart munin-node

- name: Ensure munin-node is running.
  ansible.builtin.service: name=munin-node state=started enabled=yes
